services:
  postgres:
    image: postgres:16
    container_name: traffic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trafficdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: traffic-redis
    restart: always
    ports:
      - "6380:6379"

  backend:
    build:
      context: ./backend
    container_name: traffic-backend
    restart: always
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/trafficdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: traffic-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: